api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import views

app_name = 'api'

urlpatterns = [
    url(r'jobs/(?P<slug>\w+)$' ,views.Jobsviews.as_view(), name="api_jobs"),
    url(r'company/(?P<slug>\w+)$' ,views.Company_views.as_view(), name="api_comapny"),
    url(r'user/(?P<id>\w+)$' ,views.Users_views.as_view(), name="api_users"),
    ]

app/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.HomeView.as_view()),
    url(r'how-it-works/$', views.how_it_works, name='how_it_works'),
]

jobs/urls.py
from django.conf.urls import url
from . import views

app_name = 'jobs'

urlpatterns = [
	url(r'^jobs-$', views.jobs, name='jobs'),
    url(r'^jobs/(?P<slug>[\w-]+)/$', views.job_detail, name='job_detail'),
    url(r'^browse/$', views.browse, name='browse'),
    url(r'^jobs/company/(?P<slug>[\w-]+)/$', views.job_at_company, name='job_at_company'),
]

lazher/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import logout
from accounts import views as accounts_views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('app.urls', namespace="app")),
    path('', include('company.urls', namespace="company")),
    path('', include('jobs.urls', namespace="jobs")),
    path('', include('userprofile.urls', namespace="userprofile")),
    url(r'^login/$', accounts_views.signin, name='login'),
    url(r'^password_change/$', login_required(accounts_views.password_change), name='password_change'),
    url(r'^register/$', accounts_views.signup, name='register'),
    url(r'^logout/$', logout, name ='logout'),
    url(r'^api/',include('api.urls', namespace="api")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/models.py
from django.db import models
from django.db.models import Q
from django.db.models.signals import post_save
from froala_editor.fields import FroalaField
from djmoney.models.fields import MoneyField
from django.utils.crypto import get_random_string
from company.models import Office
from django.conf import settings
from datetime import date, timedelta

User = settings.AUTH_USER_MODEL


class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.title


class Jobs(models.Model):
    JOB_TYPES_CHOICES = (
        ('Full Time', 'Full Time'),
        ('Part Time', 'Part Time'),
        ('Temporary', 'Temporary'),
        ('Intern', 'Intern'),
        ('Contractor', 'Contractor'),
        ('Other Type', 'Other Type')
    )
    title = models.CharField(max_length=100)
    slug = models.SlugField(blank=True, default='')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='jobs_category')
    office = models.ForeignKey(Office, on_delete=models.CASCADE, related_name='job_company')
    salary = MoneyField(max_digits=14, decimal_places=2, default_currency='USD')
    description = FroalaField()
    job_type = models.CharField(
        max_length=100, choices=JOB_TYPES_CHOICES, default='Full Time')
    promotion_value = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    expire_time = models.DateTimeField(null=True, blank=True)
    applied_users = models.ManyToManyField(User, blank=True, related_name='applied_users')
    saved_users = models.ManyToManyField(User, blank=True, related_name='saved_users')
    tags = models.TextField(max_length=100, default="")

    def save(self, *args, **kwargs):
        self.slug = get_random_string(length=32)
        self.tags = self.tags.split(",")
        super(Jobs, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class ApplicationInfo(models.Model):
    job = models.OneToOneField(Jobs, on_delete=models.CASCADE, related_name='application_info')
    experience = models.IntegerField(default=0)
    application_email = models.URLField(max_length=300, null=True, blank=True)
    application_url = models.URLField(max_length=300, null=True, blank=True)
    instruction = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.job.title


class CompensationInfo(models.Model):
    COMPENSATION_UNITS = (
        ('Hourly', 'Hourly'),
        ('Daily', 'Daily'),
        ('Weekly', 'Weekly'),
        ('Monthly', 'Monthly'),
        ('Yearly', 'Yearly'),
        ('One Time', 'One Time')

    )
    job = models.OneToOneField(Jobs, on_delete=models.CASCADE, related_name='compensation_info')
    amount = MoneyField(max_digits=14, null=True, blank=True, decimal_places=2, default_currency='USD')
    unit = models.CharField(max_length=100, choices=COMPENSATION_UNITS, default='Monthly')
    max_compensation = MoneyField(max_digits=14, null=True, blank=True, decimal_places=2, default_currency='USD')
    min_compensation = MoneyField(max_digits=14, null=True, blank=True, decimal_places=2, default_currency='USD')
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.job.title


class CustomAttribute(models.Model):
    job = models.ForeignKey(Jobs, on_delete=models.CASCADE, related_name='custom_attributes')
    attribute = models.CharField(max_length=100, null=True, blank=True)
    value = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.key


def application_info_created_receiver(sender, instance, created, *args, **kwargs):
    if created:
        ApplicationInfo.objects.create(job=instance)


post_save.connect(application_info_created_receiver, sender=Jobs)


def compensation_info_created_receiver(sender, instance, created, *args, **kwargs):
    if created:
        CompensationInfo.objects.create(job=instance)


post_save.connect(compensation_info_created_receiver, sender=Jobs)

jobs/views.py
from django.shortcuts import render
from .models import Jobs
from company.models import Company
from django.conf import settings
from django.http import JsonResponse
from django.core import serializers
from json import loads as json_loads
from django.core.paginator import Paginator

def jobs(request):
    query = request.GET.get('keywords')
    location = request.GET.get('location')
    order = request.GET.get('order_by')
    per_page = request.GET.get('per_page')
    page_num = request.GET.get('page',1)

    if query:
        results = Jobs.objects.filter(title__icontains=query)
        title = query + " Jobs" + " | " + settings.SITE_NAME
	    
        if location:
            results = Jobs.objects.filter(office__company__city__icontains=location)
            title = query + " Jobs " + "in " + location + " | " + settings.SITE_NAME
	        
    if location:
        title = "All jobs in " + location + " | " + settings.SITE_NAME
        results = Jobs.objects.filter(title__icontains=query, office__company__city__icontains=location)

    elif not query and not location:
        title = "Job results"
        results = Jobs.objects.all()

    if order:
        results = results.order_by(order)
    else:
        order = "-created"
        results = results.order_by("-created")

    if per_page:
        paginator = Paginator(results, per_page)
    else:
        per_page = 9
        paginator = Paginator(results, per_page)

    results = paginator.get_page(page_num)


    context = {
        'title': title,
        'items': results,
        'location': location,
        'query': query,
        'order':order,
        'per_page':per_page,
        'page_num':page_num,
    }
    
    return render(request, 'jobs.html', context)


def browse(request):
    company = Company.objects.all()
    title = 'Browse Jobs' + " | " + settings.SITE_NAME
    context = {
        'title':title,
        'company':company,
    }
    return render(request, 'browse.html', context)


def job_at_company(request, slug):
    company = Company.objects.get(slug=slug)
    results = Jobs.objects.filter(office__company__slug=slug)
    title = 'Jobs at ' + str(company) + " | " + settings.SITE_NAME
    context = {
        'title':title,
        'company':company,
        'items':results
    }

    return render(request, 'jobs.html',context)


def job_detail(request,slug):
    jobs = Jobs.objects.get(slug=slug)
    title = str(jobs) + " | " + settings.SITE_NAME
    context = {
        'title':title,
        'jobs':jobs,
    }
    return render(request, 'job_detail.html', context)

jobs/templates/browse.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load thumbnail %}
<section class="overlape">
	<div class="block no-padding">
		<div data-velocity="-.1" style="background: url(&quot;images/resource/mslider1.jpg&quot;) 50% -66.3px repeat scroll transparent;" class="parallax scrolly-invisible no-parallax"></div>
		<div class="container fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="inner-header">
						<h3>Browse Jobs</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<section>
	<div class="block less-top">
		<div class="container">
			 <div class="row">
			 	<aside class="col-lg-3 column margin_widget">
			 		<div class="widget">
			 			<div class="search_widget_job">
			 				<div class="field_w_search">
			 					<input id="browse_by_keyword" name="keyword" type="text" placeholder="Search Keywords" />
			 					<i class="la la-search"></i>
			 				</div>
			 				<div class="field_w_search">
			 					<input type="text" placeholder="All Locations" />
			 					<i class="la la-map-marker"></i>
			 				</div>
			 			</div>
			 		</div>
			 		<div class="widget border">
			 			<h3 class="sb-title open">Specialism</h3>
			 			<div class="specialism_widget">
			 				<div class="simple-checkbox">
								<p><input type="checkbox" name="spealism" id="as"><label for="as">Accountancy (2)</label></p>
								<p><input type="checkbox" name="spealism" id="asd"><label for="asd">Banking (2)</label></p>
								<p><input type="checkbox" name="spealism" id="errwe"><label for="errwe">Charity & Voluntary (3)</label></p>
								<p><input type="checkbox" name="spealism" id="fdg"><label for="fdg">Digital & Creative (4)</label></p>
								<p><input type="checkbox" name="spealism" id="sc"><label for="sc">Estate Agency (3)</label></p>
								<p><input type="checkbox" name="spealism" id="aw"><label for="aw">Graduate (2)</label></p>
								<p><input type="checkbox" name="spealism" id="ui"><label for="ui">IT Contractor (7)</label></p>
			 				</div>
			 			</div>
			 		</div>
			 		<div class="widget border">
			 			<h3 class="sb-title open">Team Size</h3>
			 			<div class="specialism_widget">
			 				<div class="simple-checkbox">
								<p><input type="checkbox" name="spealism" id="t1"><label for="t1">1 - 10</label></p>
								<p><input type="checkbox" name="spealism" id="t2"><label for="t2">100 - 200</label></p>
								<p><input type="checkbox" name="spealism" id="t3"><label for="t3">201 - 301</label></p>
								<p><input type="checkbox" name="spealism" id="t4"><label for="t4">301 - 401</label></p>
								<p><input type="checkbox" name="spealism" id="t5"><label for="t5">401 - 501</label></p>
								<p><input type="checkbox" name="spealism" id="t6"><label for="t6">501 - 601</label></p>
								<p><input type="checkbox" name="spealism" id="t7"><label for="t7">601 - 701</label></p>
			 				</div>
			 			</div>
			 		</div>
			 		<div class="widget border">
			 			<h3 class="sb-title open">Since</h3>
			 			<div class="range_slider">
			 				<div class="nstSlider" data-range_min="1990" data-range_max="2018"  data-cur_min="1991"    data-cur_max="2007">
							    <div class="bar"></div>
							    <div class="leftGrip"></div>
							    <div class="rightGrip"></div>
							</div>
							<div class="leftLabel"></div>
							<div class="rightLabel"></div>
			 			</div>
			 		</div>
			 	</aside>
			 	<div class="col-lg-9 column">
			 		<div class="filterbar">
			 			<p>Total of 145 Employer</p>
			 			<div class="sortby-sec">
			 				<span>Sort by</span>
							<select data-placeholder="20 Per Page" class="chosen">
								<option>30 Per Page</option>
								<option>40 Per Page</option>
								<option>50 Per Page</option>
								<option>60 Per Page</option>
							</select>
			 			</div>
			 		</div>
			 		<div class="emply-list-sec">
			 			<div class="row" id="masonry">
			 				{% for i in company %}
			 				<div id="jobs" class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
					 			<div class="emply-list box">
					 				<div class="emply-list-thumb">
					 					<a href="/company/{{i.slug}}" title="">
						 					{% thumbnail i.logo "80x80" crop="center" as im %}
	    										<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
											{% endthumbnail %}
										</a>
					 				</div>
					 				<div class="emply-list-info">
					 					<h3><a href="/company/{{i.slug}}" title="">{{i.title}}</a></h3>
					 					<span>Accountancy, Human</span>
					 					<h6><i class="la la-map-marker"></i> {{i.city}}, {{i.country.name}}</h6>
					 				</div>
					 			</div>
					 		</div>
					 		{% endfor %}
					 		<div class="col-lg-12">
					 			<div class="pagination">
									<ul>
										<li class="prev"><a href=""><i class="la la-long-arrow-left"></i> Prev</a></li>
										<li><a href="">1</a></li>
										<li class="active"><a href="">2</a></li>
										<li><a href="">3</a></li>
										<li><span class="delimeter">...</span></li>
										<li><a href="">14</a></li>
										<li class="next"><a href="">Next <i class="la la-long-arrow-right"></i></a></li>
									</ul>
								</div>
							</div>
						</div>
			 		</div>
				</div>
			 </div>
		</div>
	</div>
</section>
{% endblock %}

jobs/templates/job_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load thumbnail %}
<section class="overlape">
		<div class="block no-padding">
			<div data-velocity="-.1" style="background: url({{jobs.company.logo.url}}) repeat scroll 50% 422.28px transparent;" class="parallax scrolly-invisible no-parallax"></div>
			<div class="container fluid">
				<div class="row">
					<div class="col-lg-12">
						<div class="inner-header">
							<h3>{{jobs.title|capfirst}}</h3>
						</div>
					</div>
				</div>
			</div>
		</div>
</section>
<section>
		<div class="block">
			<div class="container">
				<div class="row">
				 	<div class="col-lg-8 column">
				 		<div class="job-single-sec">
				 			<div class="job-single-head2">
				 				<div class="job-title2"><h3>{{jobs.title}}</h3><span class="job-is ft">{{jobs.job_type}}</span><i class="la la-heart-o"></i></div>
				 				<ul class="tags-jobs">
				 					<li><i class="la la-map-marker"></i>{{jobs.office.company.city}}</li>
				 					<li><i class="la la-money"></i> Monthly Salary : <span>{{jobs.salary}}</span></li>
				 					<li><i class="la la-calendar-o"></i> Post Date: {{jobs.created|date:"F d Y"}} </li>
				 				</ul>
				 				<span><strong>Roles</strong> :
				 					Coming Soon
				 				</span>
				 			</div>
				 			<div class="job-details">
				 				<h3>Job Description</h3>
				 				{{jobs.description|safe|linebreaks}}
				 			</div>
				 			<div class="share-bar">
				 				<span>Share</span><a href="#" title="" class="share-fb"><i class="fab fa-facebook-f"></i></a><a href="#" title="" class="share-twitter"><i class="fab fa-twitter"></i></a>
				 			</div>
							<div class="apply-btn">
								<a href="#" title="" class="apply-job-btn"><i class="la la-paper-plane"></i>Apply for job</a>
							</div>
				 		</div>
				 	</div>
				 	<div class="col-lg-4 column">
				 		<div class="job-single-head style2">
			 				<div class="job-thumb">
			 					{% thumbnail jobs.office.company.logo "124x124" crop="center" as im %}
			 					<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
								{% endthumbnail %}
							</div>
			 				<div class="job-head-info">
			 					<h4>{{jobs.office.company.title|capfirst}}</h4>
			 					<span>{{jobs.office.city}}</span>
			 					<p><i class="la la-unlink"></i>{{jobs.office.company.website}}</p>
			 					<p><i class="la la-phone"></i> +90 538 963 54 87</p>
			 					<p><i class="la la-envelope-o"></i>{{jobs.office.company.email}}</p>
			 				</div>
			 				<a href="/jobs/company/{{jobs.office.company.slug}}" title="" class="viewall-jobs">View all Jobs</a>
			 			</div>
				 	</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

jobs/templates/jobs.html
{% extends 'base.html' %}
{% block content %}
{% load thumbnail %}
{% load static %}
<section class="overlape">
		<div class="block no-padding">
			<div data-velocity="-.1" style="background: #005980;" class="parallax scrolly-invisible no-parallax"></div>
			<div class="container fluid">
				<div class="row">
					<div class="col-lg-12">
						<div class="inner-header wform">
							<div class="job-search-sec">
								<div class="job-search">
									<h4>Explore Thousand Of Jobs With Just Simple Search...</h4>
									<form method="GET" action="jobs-" class="search-form" data-endpoint='{% url "jobs:jobs" %}'>
										<div class="row">
											<div class="col-lg-7">
												<div class="job-field">
													<input value="{{query}}" name="keywords" type="text" placeholder="Job title, keywords or company name" />
													<i class="la la-keyboard-o"></i>
												</div>
											</div>
											<div class="col-lg-4">
												<div class="job-field">
													<input value="{{location}}" type="text" placeholder="City, province or region" name="location" />
													<i class="la la-map-marker"></i>
												</div>
											</div>
											<div class="col-lg-1">
												<button type="submit"><i class="la la-search"></i></button>
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
</section>
<section>
		<div class="block result-block" id="main_results">
			<div class="container result-container">
				 <div class="row">
				 	<div class="col-lg-12">
				 		<span class="emlthis"><a href="mailto:example.com" title=""><i class="la la-envelope-o"></i> Email me Jobs Like These</a></span>
				 		<div class="filterbar">
				 			<h5 id="result-count">{{items.paginator.count}} Jobs &amp; Vacancies</h5>
				 			<div class="sortby-sec">
				 				<span>Sort by</span>
				 				<select data-placeholder="Most Recent" class="chosen sort-order" style="display: none;" data-endpoint='{% url "jobs:jobs" %}'>
									<option {% if order == "-created" %} selected {% endif %} value="?keywords={{query}}&location={{location}}&page={{ num }}&order_by=-created&per_page={{per_page}}">Most Recent</option>
									<option {% if order == "title" %} selected {% endif %} value="?keywords={{query}}&location={{location}}&page={{ num }}&order_by=title&per_page={{per_page}}">Relevance</option>
								</select>
								<select data-placeholder="20 Per Page" class="chosen sort-per-page" style="display: none;" data-endpoint='{% url "jobs:jobs" %}'>
									<option value="?keywords={{query}}&location={{location}}&page={{ page_num }}&order_by=created&per_page=9" {% if per_page == "9" %} selected {% endif %} >9 Per Page</option>
									<option value="?keywords={{query}}&location={{location}}&page={{ page_num }}&order_by=created&per_page=12" {% if per_page == "12" %} selected {% endif %} >12 Per Page</option>
									<option value="?keywords={{query}}&location={{location}}&page={{ page_num }}&order_by=created&per_page=15" {% if per_page == "15" %} selected {% endif %} >15 Per Page</option>
									<option value="?keywords={{query}}&location={{location}}&page={{ page_num }}&order_by=created&per_page=18" {% if per_page == "18" %} selected {% endif %} >18 Per Page</option>
								</select>
				 			</div>
				 		</div>
				 		<div class="job-grid-sec" id="job-search-results">
							<div class="row search-result">
								{% for i in items %}
								<div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
									<div class="job-grid border">
										<div class="job-title-sec">
											<div class="c-logo"> {% thumbnail i.office.company.logo "235x115" corp="centre" format="PNG" as im %} <center><img src="{{ im.url }}"></center> {% endthumbnail %} </div>
											<h3><a href="/jobs/{{i.slug}}" title="">{{i.title}}</a></h3>
											<h3><a href="/company/{{i.office.company.slug}}" title="">{{i.office.title}}</a></h3>
											<span>{{i.office.company.title}}</span>
											<span class="fav-job"><i class="la la-heart-o"></i></span>
										</div>
										<span class="job-lctn">{{i.office.company.city}}</span>
										<a href="/jobs/{{i.slug}}" title="">APPLY NOW</a>
									</div>
								</div>
								{% empty %}
									<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
										<div class="no-results-found"><h3>No jobs found for {{ query }}</h3>
										</div>
									</div>
								{% endfor %}
							</div>
						</div>
						{% if items.has_next or items.has_previous %}
						<div class="pagination">
							<ul>
							  {% if items.has_previous %}
							    <li class="prev"><a href="?keywords={{query}}&location={{location}}&page={{ items.previous_page_number }}&order_by={{order}}&per_page={{per_page}}" class="page-next-prev" data-endpoint='{% url "jobs:jobs" %}'><i class="la la-long-arrow-left"></i> Prev</a></li>
							  {% endif %}
							  {% for num in items.paginator.page_range %}
							    {% if items.number == num %}
							    <li class="active"><a href="?keywords={{query}}&location={{location}}&page={{ num }}&order_by={{order}}" class="page-next-prev" data-endpoint='{% url "jobs:jobs" %}'>{{ num }}</a></li>
							    {% elif num > items.number|add:'-3' and num < items.number|add:'3' %}
							    <li><a href="?keywords={{query}}&location={{location}}&page={{ num }}&order_by={{order}}&per_page={{per_page}}" class="page-next-prev" data-endpoint='{% url "jobs:jobs" %}'>{{ num }}</a></li>
							    {% endif %}
							  {% endfor %}
							  {% if items.has_next %}
							    <li class="next"><a href="?keywords={{query}}&location={{location}}&page={{ items.next_page_number }}&order_by={{order}}&per_page={{per_page}}" class="page-next-prev" data-endpoint='{% url "jobs:jobs" %}'>Next <i class="la la-long-arrow-right"></i></a></li>
							  {% endif %}
							</ul>
						</div>
						{% endif %}
				 	</div>
				 </div>
			</div>
		</div>
</section>
{% endblock %}